### ISSUE TITLE
1.1.0-1 installer version of nlmixr: command line suggestion misleading 

### ISSUE THREAD

**Issue by nholford** [nlmixrdevelopment/nlmixr#148]
I notice that the instruction about how to source a script with keep.source=TRUE is misleading.
The error message contains this:
Try running R -e 'source("script", keep.source=TRUE) instead.'

That does not work from the Windows command line. This does:
R -e "source(‘script', keep.source=TRUE)"

**Comment by mattfidler** [comment]
This needs to be fixed.

**Comment by mattfidler** [comment]
I think it should also talk about how to run "R CMD BATCH" too...

**Comment by mattfidler** [comment]
I have updated the error message.

**Comment by nholford** [comment]
It is not possible to use the -e option with CMD BATCH so nlmixr won't work with CMD BATCH. The keep.source=TRUE option is required by nlmixr since 1.0.0-8 was released but it is still not clear to me why.  By adding the echo=TRUE option to the source() command then the script commands are echoed to the output which may make the output easier to understand and parse with other tools.

R -e "source(‘script', keep.source=TRUE, echo=TRUE)"

The source command is documented here:
https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/source

Using Rscript instead of R is another way of running R from the command line:

Rscript -e "source(‘script', keep.source=TRUE, echo=TRUE)"

This is a good introduction to Rscript:
https://swcarpentry.github.io/r-novice-inflammation/05-cmdline/

**Comment by mattfidler** [comment]
I think it was a bug in the R vesion that used nlmixr.  The code has not changed since that version.

Part of the domain specific nlmixr language uses comments `#`, so the source must be kept to get this information.

If I could figure out how to set R options from the environmental variable, I could simply change the `keep.source` option globally:

From https://stat.ethz.ch/R-manual/R-devel/library/base/html/options.html


> `keep.source`:
>When TRUE, the source code for functions (newly defined or loaded) is stored internally allowing comments to be kept in the right places. Retrieve the source by printing or using deparse(fn, control = "useSource").
>
>The default is interactive(), i.e., TRUE for interactive use.


While you can set it `TRUE` in your code, it already parsed the script while evaluating so it has no use unless sourcing another file.  Therefore the following does not work:

```R
options(keep.source=TRUE)
f <- function(){
## nlmixr model specification
}
fit <- nlmixr(f,data,est) ## does not work
```

But the following would work:

```R
options(keep.source=TRUE)
source("file-with-nlmixr-models.R")
```
I was thinking of creating a linux/unix shell script and windows executable that does this (say nlmixr.sh or nlmixrBatch.exe) that would allow running a modified `R CMD BATCH filename.R` that sources the file in the manner above by creating a temporary R script that sets the working directory and keep-source option and sources the original nlmixr model run.

**Comment by nholford** [comment]
I can confirm that the error message generated by nlmixr when keep.source is not TRUE has now been corrected in 1.1.0-3. Thanks.

I still don't understand why this problem using R CMD BATCH appeared in 1.0.0-8. Can you try and explain what change you made in 1.0.0-8 that requires keep.source=TRUE? I believe it has something to do with the way nlmixr reads the information in the model function. Can you give an example of how this has changed in 1.0.0-8 et seq?

Your special shell script/executable method may work but I can live  with calling R with the -e option if you can find a way to send lines such as the following to stdout. At the moment they only appear on the console and not in stdout so I cannot capture them in a file.

-- nlmixr FOCEi fit ------------------------------------------------------------

-- Time (sec; pkpd.fit.CEF$time): ----------------------------------------------

-- Population Parameters (pkpd.fit.CEF$parFixed): ------------------------------

Note these are just examples of the kind of output I want to capture. Can you send all nlmixr generated output that starts with '-- ' to stdout?

**Comment by mattfidler** [comment]
Let me think about something or implementing a separate executable.

Note that 1.0.0-7 also has the same error:

https://github.com/nlmixrdevelopment/nlmixr/blob/e4486b25db7e6b63b61ccec137a4733c0052c183/R/ui.R#L91

So nothing has changed between the versions except for the version of R.

**Comment by nholford** [comment]
I didn't get any errors with 1.0.0-7. Your code shows that an error could be trapped but that is not the same as saying "1.0.0-7 also has the same error."
Would you please answer my question about directing nlmixr output to sysout? If you paid attention to the way nlmixr prints its output that would avoid having to create kludge scripts to work around this problem.

**Comment by mattfidler** [comment]
The error trapping is in exactly the same place, so my hypothesis is this is a R version issue.  In previous versions of R I also had the same issue.  I don't know what would have changed otherwise. To me it was a surprize that 1.0.0-7 actually didn't error on this way of running nlmixr.

In windows, you should be able to output stderr and stdout to a file using the following:

https://support.microsoft.com/en-us/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout

I have tested this with the tmp.R file and produced the tmp.Rout with the following command:

```
R -e "source('tmp.R', keep.source=TRUE, echo=TRUE)" 1> tmp.Rout 2>&1
```

The zip file shows the output files and their output; Note nothing displays on my console.

[tmp.zip](https://github.com/nlmixrdevelopment/nlmixr/files/3069764/tmp.zip)

**Comment by mattfidler** [comment]
If you are trying to parse the fit object for parameters, I think it would be easier to let R do this for you.

Running the same script it shows you can extract a data frame with all the parameter values:
```
> fit$parFixedDf
          Estimate         SE      %RSE Back-transformed   CI Lower   CI Upper BSV(CV%) Shrink(SD)%
tka      0.4623404 0.19592745 42.377312       1.58778574 1.08147915 2.33112544 73.31840    1.769089
tcl     -3.2189551 0.07544585  2.343799       0.03999683 0.03449896 0.04637087 26.94915    3.971853
tv      -0.7781355 0.04144856  5.326651       0.45926152 0.42342742 0.49812821 13.66706   10.289765
add.err  0.6889895         NA        NA       0.68898945         NA         NA       NA          NA
```

Which can be output to a csv file easily:

```R
write.csv(fit$parFixedDf, file="theo-est.csv", na=".")
```
The result is the file contained in [theo-est.zip](https://github.com/nlmixrdevelopment/nlmixr/files/3069809/theo-est.zip)

**Comment by nholford** [comment]
I have no problem finding the parameter estimates in stdout.

What I cannot find is the name of the nlmixr model used to create the output in stdout. As I have told you several times I can find this information on the console but not in stdout. Why don't you answer my question about directing nlmixr output to stdout?  I've asked more than once. This is becoming a problem for me to continue spending a lot of time trying to help you with nlmixr when you ignore my questions.

**Comment by mattfidler** [comment]
I thought I answered the question; You use the following command:

```
R -e "source('tmp.R', keep.source=TRUE, echo=TRUE)" 1> tmp.Rout 2>&1
```

**Comment by mattfidler** [comment]
Let me know if it doesn't work.

**Comment by nholford** [comment]
My apologies, Matt. I missed that bit of the thread where you suggest piping both stderr and stdout to the same file. I've tested it and now I get the missing bits of information I needed to parse the output and connect to the models that were run. Thanks for this which now means I can use 1.1.0-3 on my Windows Server 2012 platform.

**Comment by mattfidler** [comment]
I think this comment is more or less fixed based on our conversation.  

In windows it issues:
```
Cannot run this way in non-interactive mode.
Try running:

R -e 'source("script", keep.source=TRUE)'

For Batch-mode type of running, you can use:

R -e "source('script.R', keep.source=TRUE, echo=TRUE)" 1> script.Rout 2>&1
```
