### ISSUE TITLE
M4 method for handling BLQ data

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#182]
Hi @mattfidler ,

Does current version of nlmixr supports M4 method of handling BLQ data?

**Comment by mattfidler** [comment]
Sorry for the delay @karthikl6 

The current version of nlmixr does not do anything special for BLQ data, though that is indeed on the todo list.

**Comment by billdenney** [comment]
@mattfidler, If I understood our discussion at ACoP correctly, there is a slow, manual way to calculate custom likelihood directly in R.  While I understand that there could be a notable hit to performance, is that documented?  (I will understand if the answer is, "No, because we don't want to support that long-term.")

**Comment by mattfidler** [comment]
Yes.
`?gnlmm` and `?gnlmm2`

**Comment by mattfidler** [comment]
Also draft `M4` and other methods are in the development branch, if you are
brave and want to drop python.

**Comment by mattfidler** [comment]
Will be in the next release
