### ISSUE TITLE
CRAN dependency on RxODE not available

### ISSUE THREAD

**Issue by rfaelens** [nlmixrdevelopment/nlmixr#187]
The current nlmixr version on CRAN (`1.1.0-9`) depends on RxODE `≥ 0.9.0-6`.
However, that version does not exist on CRAN...

https://cran.r-project.org/web/packages/RxODE/index.html

Will it be released soon?
It seems CRAN messed up?
Last commit on CRAN github: https://github.com/cran/RxODE/commits
However, r-pkg reports 0.9.0-6 https://www.r-pkg.org/pkg/RxODE

**Comment by mattfidler** [comment]
Hi @rfaelens, it was already released; You can see it on the archive:

https://cran.r-project.org/src/contrib/Archive/RxODE/

Because it failed a test on a specific system, that version was pulled from CRAN and rolled back to a prior version.  In the past the whole package was pulled from CRAN, this seems to be a change in policy or perhaps because RxODE is gaining popularity.

CRAN did not roll back `nlmixr` when you posted the issue, however.   

The following shows the releases to CRAN:

https://cran.r-project.org/src/contrib/Archive/nlmixr/

Which now includes the new release too.  Now CRAN has rolled back to the prior release of nlmixr that works with the old RxODE.

So, CRAN didn't exactly mess up, but took a few days to sync with what it did when rolling back RxODE.
