### ISSUE TITLE
Corrector covergence failed repeatedly with FOCEi

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#197]
Hi @mattfidler ,

I'm trying to understand what this error means? I'm currently using FOCEi algorithm to fit an indirect response model. Could you please let me know what this means?

![image](https://user-images.githubusercontent.com/20660426/60967076-cbb08880-a2e7-11e9-8c63-17d24aa6cff7.png)

**Comment by tamas-ferenci** [comment]
Here is a reproducible example which produces similar errors:

```
library( nlmixr )

one.compartment.saem <- function() {
  ini({
    tka <- -3   # Log Ka
    tcl <- -3.2 # Log Cl
    tv <- -1    # Log V
    eta.ka ~ 1
    eta.cl ~ 2
    eta.v ~ 1
    add.err <- 0.1
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v 
    cp ~ add(add.err)
  })
}

nlmixr( one.compartment.saem, theo_sd, est = "focei" )
```

In an other case, I obtained similar error messages:
```
unhandled error message: EE:lsoda -- at t = 108.855 and step size _C(h) = 3.80974e-10, the
 @(         error test failed repeatedly or
         with fabs(_C(h)) = hmin
:54709048
```
(so we have `error test` instead of `corrector`).

**Comment by mattfidler** [comment]
These are ode solving errors.  

When `FOCEi` encounters ODE solving problems it temporarily reduces the tolerances up to a limit and resolves.  This allows a less accurate answer but allows the optimization to progress.  You should be (slightly) concerned if this occurs on the last step of optimization, otherwise the final answer should have the requested accuracy (by default I think it is equivalent of 4 sigdigs;  Note this sigdig definition is **different** from NONMEM's sigdig definition).

**Comment by mattfidler** [comment]
If you need more help here, let me know.
