### ISSUE TITLE
Timeout in nlmixr

### ISSUE THREAD

**Issue by tamas-ferenci** [nlmixrdevelopment/nlmixr#198]
Is it possible to run an `nlmixr` call with timeout? (I.e. return - for example - `NULL` if not finished within X seconds.)

The `R.utils::withTimeout` would be the usual tool, but it doesn't seem to work:

```
R.utils::withTimeout( nlmixr(one.compartment.saem, theo_sd, est="saem"), timeout = 5 )
```

It gives an error, but then goes further as if nothing happened.

Also, I don't seem to be able to catch this error:

```
tryCatch( R.utils::withTimeout( nlmixr(one.compartment.saem, theo_sd, est="saem"),
          timeout = 5 ),
          error = function( e ) message( "Error" ),
          TimeoutException = function(ex) message("Timeout") )
```

Finally, `nlmixr` has no built-in timeout option (as far as I know!), so now I am stuck...

**Comment by mattfidler** [comment]
This is because you are trying to time-out a compiled function in R, which doesn't work very well.

Currently `saem` has no time-out options.

**Comment by mattfidler** [comment]
It may be difficult to time-out `saem` because you would have to choose when to check.  Depending on the length of the ODE solving, it may take much more time before it stopps.

**Comment by tamas-ferenci** [comment]
Thanks @mattfidler for the quick reply! All in all, does it mean that there's no solution or workaround for this problem? (Is it true for `focei` as well?)

**Comment by mattfidler** [comment]
For now, there is no solution.  There may be in the future

For FOCEi it depends on the outer optimization routine.  The `nlminb` and `bobyqa` which really do a good job in optimization have a maximum number of evaluations, but not a time-out function.  

You would have to find another optimization routine with a timeout in it (I have seen them in the past), and use them instead of the two above.  The answers may be different with the different optimization routines.

**Comment by tamas-ferenci** [comment]
Thank you very much again!
