### ISSUE TITLE
Estimation using FOCEi and FO

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#239]
Hello,

I am running a model with many covariates (50+) trying to identify their effect. I came upon a situation where "focei" will not quantify any of the effects, as in big error and confidence interval crossing zero but "fo" will quantify the majority of the effects. Can I trust the results from "fo" and any idea as to what could be the reason behind that difference?

**Comment by mattfidler** [comment]
The `fo` method optimizes on the whole population based on a approximation of the mixed effect model likelihood.  While clever, it doesn't actually make sure the underlying assumptions are correct in the data.  Hence, you may pick up more covariates than could be described by between-subject variability.  

The `focei` estimates each individuals best fit (optimized in the "inner" step) and then uses these conditional estimates to calculate the likelihood, which is then optimized by the "outer" step.  While it is still a first order approximation to the likelihood function, it is more robust since it is conditioned on the best estimate for each estimate.  

For problems where the amount of unexplained variability depends on the model prediction (like proportional error), the interaction term calculates the inter-dependence of the unexplained variability and individual estimates (making it even more robust).

So, since `focei` is more robust than `fo`, I trust the estimates from that procedure more than the estimates from `fo`.  I believe the pharmacometric community shares the same viewpoint, though uses `fo` from time to time even though they understand it ins't the best method.

**Comment by DimitrisVoul** [comment]
Thank you very much for that thorough answer. Probably an naive question but is that the case for covariates that are added as fixed effects?

Meaning that in my model these covariates make a contribution to the population prediction rather than the individual and have no ETAs tied to them.

**Comment by mattfidler** [comment]
Yes.  It is true when the covariates are added as fixed effects.  Its more
of the path of optimization and underlying assumptions.

**Comment by DimitrisVoul** [comment]
Thank you very much!
