### ISSUE TITLE
Vpc error: 'Calloc' could not allocate memory (225120500 of 320 bytes)

### ISSUE THREAD

**Issue by karthikl6** [nlmixrdevelopment/nlmixr#266]
Hi @mattfidler ,

I'm trying to generate VPC, but was throwing error as shown below. It works only if n<100, and not sure if this is a memory issue (RAM 16 GB on my computer)?
![image](https://user-images.githubusercontent.com/20660426/71081198-bffda380-215c-11ea-9a6f-d5ccc544dbb5.png)

Regards,
Karthik

**Comment by mattfidler** [comment]
Unfortunately this is a memory issue

The current procedure is:

`data -> etTrans -> copy to C -> solve in parallel -> copy to R`

Therefore it makes 3 different sized copies of the data to solve.  The etTrans is necessary to setup the data.  The Copy to C is required to run in parallel, and the copy to R is required to get it out of the simulation. 

The size of `data` and `etTrans` are similar.  The copy to C also allocates new data for each solve (but points to the data instead of using directly), so it is larger than `etTrans`.  The largest allocation is the final dataset which doesn't use memory pointers to save space.

You could run the vpc 100 at a time and then bind them together.  It would be good to automate this, but it hasn't been added. 

 and the copy to R allocates the memory for the output dataset.

**Comment by mattfidler** [comment]
For me, I haven't hit this barrier with a simple problem, but it could be problematic with large datasets.

**Comment by mattfidler** [comment]
You could subdivide it or restart R.
