### ISSUE TITLE
Truncated covariate

### ISSUE THREAD

**Issue by DimitrisVoul** [nlmixrdevelopment/nlmixr#293]
Hello,

Not an issue exactly but more of a question on functionality. Is there a way to implement a restriction on the a covariate that extents to the individual values?

What I mean is that I have a parameter that needs to be between zero and one and not just the mean value THETA but all individual values (otherwise is mechanistically/biologically wrong). I was wondering if there is a way to impose that other than a transformation of the form:

Cov1<-exp(theta+eta)/(1+theta+eta)

As I have found that this makes computations slower and the optimisation to get stuck as the plateaus ever so often. 

Any help would be really appreciated.

**Comment by mattfidler** [comment]
I'm not sure if it would get stuck in the plateaus or not, but you could use an `if/else` clause

```
Cov1 <- theta+eta
if (cov1 > 1) { 
   cov1 = 1
}
if (cov1 < 0) {
 cov1 = 0
}

**Comment by DimitrisVoul** [comment]
I tried to do that but I get an error for focei saying that:  if/else depends on ETAs, currently not supported by FOCEi/CWRES.

**Comment by mattfidler** [comment]
I'm unsure how to do it currently then;  It probably gets stuck because of slow slopes;  This is why machine learning adopted the `relu` activation unit.

Based on the context of a `relu` unit, machine learning used to use `tanh` instead and had better results with it;  Therefore a `tanh` may be a better approach.  I believe that `tanh` should be supported.  

See the text below for a discussion:

https://machinelearningmastery.com/rectified-linear-activation-function-for-deep-learning-neural-networks/

**Comment by mattfidler** [comment]
Something like:

```{r}
0.5*tanh(theta+eta)+0.5
```

**Comment by DimitrisVoul** [comment]
That's a good suggestion thank you. I will give it a try.

**Comment by mattfidler** [comment]
Hopefully it worked.  For now I will close the issue.
