### ISSUE TITLE
`fo` without a posthoc step?

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/nlmixr#351]
Should data be predicted for `fo` without a posthoc step?

**Comment by billdenney** [comment]
I don't know if this is the same or different, but the AIC method for an `fo` object works differently.  When I'm running AIC on two `fo` objects, I get:

```
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
```

I can make a reprex if needed, but if all of the other changes here will fix it because it becomes a different object type, that seems unnecessary.

**Comment by mattfidler** [comment]
Please make a reprex;  As it stands, the FO method shows 2 objective functions:

1 - The objective function for the `fo` method
2 - The objective function for the `foce` posthoc step.

This seems like a bug.

**Comment by mattfidler** [comment]
There is some discussion of 2 different objective function metrics on the broom vignette:

https://nlmixrdevelopment.github.io/nlmixr/articles/broom.html

**Comment by mattfidler** [comment]
I'm going to leave this as is for now.
