### ISSUE TITLE
Feature Request: Arbitrary variable to define residual error

### ISSUE THREAD

**Issue by jpryby** [nlmixrdevelopment/nlmixr#367]
Hi Matt,

This is based on #231. You offered a good solution, but I'm hoping it can be made easier.

Is there a way we can simplify multiple error model systax without requiring data manipulation? I'm porting some NONMEM models over to nlmixr and finding that the worst ones are those that define RUV with a THETA especially when there are covariate options that modify RUV. It seems nlmixr can only have errors that are defined as THETAs, which is like if NONMEM only allowed errors defined in $SIGMA. The known workarounds in NONMEM aren't consistent with the workaround for nlmixr so I'm worried it's not as intuitive as it can be.

Could we have it so a variable can be declared in the model that is valid to be used as the residual error term? Such as:

```
RUV_SD = TVRUV
if (DOSE>100) RUV_SD = 0.2 + TVRUV
...
linCmt()~add(RUV_SD)
```

John

**Comment by mattfidler** [comment]
Thank you for bringing this up. I agree that this is not the way that NONMEM handles things, so it may not be intuitive on how to handle things if you are coming from NONMEM.

However the same can be said about coming from Monolix, they handle things differently too.  Part of this is the ways the estimation algorithms are different between the two packages. 

However, what you propose is not easy to implement in nlmixr based on how multiple estimation methods currently work and how each differently define residuals.  Rather than rewrite the entire estimation methods, and the entire user interface right now I will stick with the work-arounds. 

Thank you for your understanding.

**Comment by mattfidler** [comment]
One of the things I was thinking of was having nlmixr change endpoints from wide to long format automatically to handle something like the fed/fast example, but that isn't what was suggested here.

**Comment by jpryby** [comment]
Cheers Matt, makes sense. Alternatively, making it so the multiple endpoint can be flagged from any column (not just cmt or dvid) would be another automatic way to do it without changing the algorithm.
Something like:
```
cp~prop(RUV) | FED=0
cp~prop(RUV_FEDCOV) | FED=1
```

**Comment by mattfidler** [comment]
That may be possible, and will require more work than simply stacking the data.
