### ISSUE TITLE
Model SC and IV dosing simultaneously?

### ISSUE THREAD

**Issue by KyleBarrett** [nlmixrdevelopment/nlmixr#47]
Is it possible to have extravascular and intravascular dosing regimens within the same nnlmixr model?

**Comment by mattfidler** [comment]
Yes, it is when using ODEs.

If you are talking about subcutaneous + IV it would just be adding a the correct event information to input data set.  If you are familiar with nonmem, the easiest way to do this is to use the `nmDataConvert` function.  Otherwise you code the events in the `EVID` column; 

The `EVID`s match the evid definition of RxODE

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html

**Comment by mattfidler** [comment]
Therefore a bolus dose to compartment 1 would be `101` and a Infusion/zero order release would start with `100101` with the amount defining the zero order release rate.  It would stop with `100101` with a negative amount removing that zero order release rate.

**Comment by KyleBarrett** [comment]
Thanks so much
