### ISSUE TITLE
parallel computing not working

### ISSUE THREAD

**Issue by sliao999** [nlmixrdevelopment/nlmixr#522]
I tried parallel computing with this pk model below. Not sure what is missing, it is running, but not using more than one core.
===============================
options("RxODE.cache.directory"="~/.rxCache")
library(nlmixr)
library(doParallel)

# define the model
nimo <- function() {
  ini({
    ## Note that the UI can take expressions
    ## Also note that these initial estimates should be provided on the log-scale
    tcl <- log(109)
    tv1 <- log(512)
    tq <- log(12)
    tv2 <- log(156)
    talpha <- log(0.171)
    tbeta <- log(1.08)
    ## Note this covariate effects take expressions
    crcl_cl<-0.32
    crcl_v1<-0.29
    race2_cl<-0.32
    form_alpha<-1.47
    stat_alpha<-1.98
    ## Initial estimates should be high for SAEM ETAs
    eta.cl  ~ .1
    eta.v1  ~ .1
    eta.v2 ~ .1
    eta.alpha ~ .1
    eta.beta ~ .01
    ##  Also true for additive error (also ignored in SAEM)
    add.err <- 0.3
  })
  model({
    CL <- exp(tcl +crcl_cl*log(crcl/110)+log(1+race2*race2_cl)+ eta.cl)
    V1 <- exp(tv1 +crcl_v1*log(crcl/110)+ eta.v1)
    V2 <- exp(tv2 + eta.v2)
    Q  <- exp(tq)
    alpha <- exp(talpha+log(1+form*form_alpha)+log(1+stat*stat_alpha) + eta.alpha)
    beta <- exp(tbeta + eta.beta)+1
    
    C1=centr/V1;
    C2=peri/V2;
  #  tad <- tad()
    WB=(beta/alpha)*((t/alpha)^(beta-1));
    d/dt(depot)=-WB*depot;
    d/dt(centr)= WB*(depot)-CL*C1-Q*C1+Q*C2;
    d/dt(peri) =+Q*C1-Q*C2;
    cp=log(C1)
    cp~add(add.err)
  })
}

# read the data
dat <- read.csv("E:/KKD/Naloxegol ped/poppk3/combined_nm.csv")
head(dat)
cl <- makeCluster(detectCores()-1)
registerDoParallel(cl)
fit <- nlmixr(nimo, dat, est="focei")

**Comment by sliao999** [comment]
I tried foreach as below, and I got error msg "Error in { : 
  task 1 failed - "'names' attribute [12] must be the same length as the vector [4]"
===============================
pars <- update( nimo )$theta.ord
set.seed( 1 )

cl <- makeCluster(detectCores()-1)
registerDoParallel(cl)

# run the model
foreach(i. = 1:100, .combine = "c") %dopar% {
  l <- setNames( c( list(nimo), runif(3,-5,5) ), c( "", pars ) )
  m <- nlmixr::nlmixr( do.call( update, l ), dat, est = "focei")
  AIC( m )
}

**Comment by mattfidler** [comment]
Hi @sliao999 

The parallelization in nlmixr is done at the `C` level and does not need to be setup with R; In fact it cannot currently be parallelized in R.  

Currently the only estimation routine that is parallelized on the C level is `saem`.  So you will not see any parallelization in any other routine with the current release

**Comment by sliao999** [comment]
Dear Matt,
Thanks for your quick reply.

When I run saem, it only use ~15% of my CPU with 32 cores. How can I set up to run all cores?
fit <- nlmixr(nimo, dat, est="saem")

Sam

**Comment by mattfidler** [comment]
Hi @sliao999 

You can specify the number  of cores with `cores = 32`.  However, the current implementation uses half of your available cores by default.  

This means that even though there are 32 cores available not all can be used in your problem.  The parallelization is per id.  If you only have `6` IDs no matter how many cores you specify the most you can solve is 6 ODEs.  Practically,  though, often the number is lower because the ODEs solve at different rates.  All IDs have to be solved before the next problem can be started. 

In SAEM, there are more parallel solving ODEs than the simple number of IDs in the system, but the same logic applies as the simple ID example.  

So if you were to use the same code as above you would use:

```r
fit <- nlmixr(nimo, dat, est="saem", control = saemControl(cores=32))
```

You can also use `setRxThreads()` described here:

https://nlmixrdevelopment.github.io/RxODE/reference/getRxThreads.html

Here you would use:

```R
setRxThreads(32, throttle = 0)
```
Hopefully this explains the situation here.

For more information about the options for running `saem` from the `saemControl()`  found [here]()

**Comment by sliao999** [comment]
Dear Matt,
Thanks for your reply.
I tried this code from you and it is still running with only 15% of the CPU. There were ~300 ID in this data.
fit <- nlmixr(nimo, dat, est="saem", control = saemControl(cores=32))

**Comment by mattfidler** [comment]
Have you tried:

```r
setRxThreads(32, throttle = 0)
fit <- nlmixr(nimo, dat, est="saem")
```

If this works, there may be a problem with the `throttle` option.

**Comment by sliao999** [comment]
Dear Matt,
I just did as you show me. It make no difference. only ~12% CPU usage.

Sam

**Comment by mattfidler** [comment]
I don't have that many cores to test the system, so I cannot reproduce unfortunately.  The only thing I can do is to remove the throttling to see if that is helpful.  Let me know if you wish tot try that.
