### ISSUE TITLE
Steady state data modeling 

### ISSUE THREAD

**Issue by melagha** [nlmixrdevelopment/nlmixr#529]
Hello,
I went through the examples posted on https://nlmixrdevelopment.github.io/nlmixr/articles/modelPiping.html
but I could not figure out how to handle  data that represent steady state PK.
Is there a way to model steady state data?

Thanks

**Comment by mattfidler** [comment]
Hi @melagha ,

`nlmxir` uses the data to figure out if there is steady state.  Since `nlmixr` uses the `RxODE` simulation engine it handles this in the same way as RxODE.  

Here is a link that describes steady state handling in nlmixr and RxODE:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html#steady-state-1

**Comment by melagha** [comment]
Awesome. 
Appreciate your prompt response.
