### ISSUE TITLE
Help request: `library(nlmixr)` failing when using version 1.1.1-5

### ISSUE THREAD

**Issue by erp31** [nlmixrdevelopment/nlmixr#532]
Firstly, thank you for your efforts on developing this package. 

I am working with version 1.1.1-5 on R 3.6.3. I appreciate that a lot of work has gone into the package since then but do not have the option of updating.
 
After a seemingly successful installation of **nlmixr**  and dependencies`library(nlmixr)` is giving me the following error:
![image](https://user-images.githubusercontent.com/56456021/121893145-8ab42080-cd15-11eb-8af5-0d68a28cefbd.png)

My feeling is that the cause is a non-R dependency problem but this error isn't giving me anything useful to diagnose the problem. I was wondering if you've seen this error before and can suggest anything that might be causing the problem? If it's relevant, `library(RxODE)` runs successfully.

The OS is redhat 7.7 eus repos. I have successfully used the same version of the package on other servers with the same OS, R packages, system dependencies and install process but it's failing on a new server. 

Any pointers would be much appreciated! I'll try to provide any additional information that you think may help you diagnose the problem. Thanks in advance.

**Comment by mattfidler** [comment]
Hi @erp31 ,  

Could you explain why you cannot upgrade?  That may help me diagnose the problem.  

My guess is you are using incompatible binaries with RxODE and nlmixr.  You can use MRAN if you want to keep the binary compatibility the same.  Simply use the same date as the `nlmixr-1.1.1-5` when installing the packages.

Since you are using redhat, you could also use git to pull the latest releases of RxODE and nlmixr and modify them to run on R `3.6`.  The 4.0 requirement was because of windows tool-chain changes from R 3 to  R 4.

**Comment by mattfidler** [comment]
It could be helpful too to try `library(RxODE)` in both the working and non-working servers to see if there is a difference in `sessionInfo()` to help diagnose the problem and possible differences between the systems.

**Comment by mattfidler** [comment]
I'm assuming you fixed this by now.
