### ISSUE TITLE
Simulation in RxODE after fitting

### ISSUE THREAD

**Issue by shaynewatson** [nlmixrdevelopment/nlmixr#64]
Hello,
I am currently trying to fit a model and then use the .rds to simulate a different dose using RxODE. Below is the current method I am using to run the simulation. It seems like I should be able to use res without making mod1 but I was unable to find a method to do so. Is there a better way to handle this simulation?

```R
create_proj(loc = ".", overwrite = TRUE) 

 proj_obj <- get_proj()

 run_nmx("run2",proj=proj_obj,ext=F) 

 res  <- readRDS("./shinyMixR/run2.res.rds")

 ev <- eventTable(amount.units="mg", time.units="hours") %>%
   add.dosing(dose=10000, nbr.doses=1, dosing.to=2) %>%
   add.sampling(seq(0,3,length.out=100)); 
 
 mod1<-RxODE(
 paste0("cl=tcl*exp(eta.cl);
        v=tv*exp(eta.v);
        ka=tka*exp(eta.ka);
        ",res$model$obj))
 modsolved<-solve(mod1,params=res$theta,ev,inits=c(0,0),
                  omega=res$omega,nSub = 10)
 x <- as.data.frame(modsolved)
 ggplot(x,aes(time,center,color=as.factor(sim.id))) + geom_line() + ylab("Central Concentration") + xlab("Time");
```
Thanks,
Shayne

**Comment by mattfidler** [comment]
Hi Shayne,

You are right, you can use the run to simulate new dosing scenarios.  The easiest way to do this is to use R's `simulate` function which cah be used with nlmixr fits.

Using your code, and your eventTable, the following code is shared:

```R
library(shinyMixR)
create_proj(loc = ".", overwrite = TRUE) 

 proj_obj <- get_proj()

 run_nmx("run2",proj=proj_obj,ext=F) 

 res  <- readRDS("./shinyMixR/run2.res.rds")

 ev <- eventTable(amount.units="mg", time.units="hours") %>%
   add.dosing(dose=10000, nbr.doses=1, dosing.to=2) %>%
   add.sampling(seq(0,3,length.out=100)); 
```

The first option (recommended for clinical trial simulations) is to sample from the uncertainty in your parameters.  The population parameters (i.e. the "theta"s) are simulated from a mutivariate normal distribution to have a realization for a virtual study.  The between subject varaibility matrix ("omega") and residual varaibility matrix ("sigma") are both simulated from inverse wishart distributions for each realization of a virtual study (with degrees of freedom of the number of subjects  for the omega matrix and the number of observations for the sigma matrix).  


This is quite easy with the following code:

```R
sim <- simulate(res,events=ev, nSub=300,nStud=300)
```

Where `nSub` is the number of subjects in each virtual study and `nStud` is the number of virtual studies.  You can see some of the properties of this simulation by summarizing certian pieces of it.  

```
> summary(sim$params)
     sim.id          eta.v                eta.ka               tka         
 Min.   :    1   Min.   :-0.9132311   Min.   :-6.720221   Min.   :-0.1456  
 1st Qu.:22501   1st Qu.:-0.0247846   1st Qu.:-0.364930   1st Qu.: 0.3450  
 Median :45001   Median :-0.0000233   Median : 0.000932   Median : 0.4782  
 Mean   :45001   Mean   : 0.0002707   Mean   :-0.000419   Mean   : 0.4783  
 3rd Qu.:67500   3rd Qu.: 0.0253130   3rd Qu.: 0.362461   3rd Qu.: 0.5920  
 Max.   :90000   Max.   : 1.0006636   Max.   : 5.850402   Max.   : 0.9509  
       tv              eta.cl                tcl        
 Min.   :-0.9139   Min.   :-1.8650400   Min.   :-3.472  
 1st Qu.:-0.8121   1st Qu.:-0.0733721   1st Qu.:-3.275  
 Median :-0.7848   Median :-0.0008324   Median :-3.221  
 Mean   :-0.7851   Mean   :-0.0008661   Mean   :-3.220  
 3rd Qu.:-0.7574   3rd Qu.: 0.0718680   3rd Qu.:-3.163  
 Max.   :-0.6711   Max.   : 1.5550696   Max.   :-2.885  
```

Here you can see that the "typical" clearance varies as well as the etas.  In addition you can see the omega/sigma matricies that are chosen for each study by:

```R
> head(sim$omega.list,3)
[[1]]
           [,1]        [,2]        [,3]
[1,] 0.53343765  0.00632114  0.05571488
[2,] 0.00632114  0.05488904 -0.01799070
[3,] 0.05571488 -0.01799070  0.03996073

[[2]]
            [,1]       [,2]        [,3]
[1,] 1.241368413 0.20987892 0.008933452
[2,] 0.209878919 0.11947895 0.012484270
[3,] 0.008933452 0.01248427 0.018430285

[[3]]
           [,1]        [,2]        [,3]
[1,] 1.37419522  0.09899824  0.01474735
[2,] 0.09899824  0.07532544 -0.01726544
[3,] 0.01474735 -0.01726544  0.01979003

> head(sim$sigma.list,3)
[[1]]
          [,1]
[1,] 0.3965163

[[2]]
          [,1]
[1,] 0.4839723

[[3]]
          [,1]
[1,] 0.5353186

```

If you are using the latest github `nlmixr` as well as dplyr/tidyr/ggplot it is easy to plot this as well:

```R
plot(sim)
```
Although it takes some time to summarize (for me longer than to simulate), eventually you get the following plot:
![image](https://user-images.githubusercontent.com/514778/43499363-b26315f4-9510-11e8-9ef6-2957bbb24c9b.png)

Of course since it is a ggplot-type object you can also modify the axes as follows:

```R
plot(sim)+ theme_light(base_size=18) + xlab("Time (hr)") + ylab("Theophylline (\u03BCg/mL)")
```

![image](https://user-images.githubusercontent.com/514778/43499461-2efede18-9511-11e8-8b3e-45aa73aa91fb.png)

You can also simulate without variability, this is a variant of the above function:

```R
sim <- simulate(res,events=ev, nSub=25000)
```

Currently this is documented in the PAGE course notes as well as `nlmixrSim`.  If you have suggestions to help the R documentation, please feel free to submit a pull request or write something.

The roxygen documentation is currently at

https://github.com/nlmixrdevelopment/nlmixr/blob/587d1b97e2f30d839d942404f69a9bd662b0b871/R/simulate.R#L76

**Comment by KyleBarrett** [comment]
Hi Matt,
Just another comment to simulate function. I tried plotting time~sim in the output data frame, and I got the following:
![image](https://user-images.githubusercontent.com/39305051/43612673-108dfe44-967b-11e8-9ecd-a12fc48ac33c.png)

The following commands showed something interesting:

> sim_dat <- simulate(res,events=ev,nSub=nsub,nStud=stud,nsim = nsim,addDosing=T,addCov=T)
Compiling model...done
> head(sim_dat)
  sim.id evid   amt time    ipred      sim
1      1  201 10000    0 47.49934 47.63676
2      1  101 20000    0 47.49934 47.35971
3      1    0    NA    0 47.49934 47.38688
4      1    0    NA    0 47.49934 46.97733
5      1    0    NA    0 47.49934 47.45549
6      1    0    NA    1 44.62742 44.70120
> plot(sim_dat$time,sim_dat$sim)
> class(sim_dat$sim)
[1] "integer"
> sim_dat$sim %>% as.numeric() %>% head()
[1] 1 1 1 1 1 1
> n_distinct(sim$sim.id)
[1] 100
> n_distinct(sim$sim)
[1] 100

This is with nSub <- 50, and nStud <-2
Plotting time ~ iPred works fine since it is of class numeric. I was wondering if the intention was for $sim to act as an ID or a concentration, like the table suggests.

Best,
Kyle

**Comment by KyleBarrett** [comment]
Hi Matt,

I've been trying to simulate multiple patients with different weights, ages, etc. They are not time varying, though I can get around this but specifying:
cov.df <- data.frame(WT = rep(5, length.out=100)) 
and then supplying this to simulate()

I wish to specify multiple weights. I figured I would do this using the expand function:
ev$expand(num_subjects), and then add dosing and time sampling to each subject, however when I execute this command per the documentation, I get "error attempt to apply non-function".

Im not sure if my syntax is wrong or if there is another way to accomplish what Im trying to do.
I know that if you dont specify an event table, simulate() will add an id column from your original dataset. So you can then cbind() the covariates from the original dataset to the simulated data frame. But I havent figured out a way to specify covariates per subject while specifying a dosing regimen via eventTable().

Best,
Kyle

**Comment by mattfidler** [comment]
Thanks Kyle,  

RxODE currently doesn't have direct support for covariate simulation with a single dataset/event table.  

You could always use a for loop and simulate a dataset and then run the RxODE model in a block in a `lapply` (faster) or `for` loop (slower).  However, it isn't quite as easy as the `simulate` in R.

A bug report is opened here:

https://github.com/nlmixrdevelopment/RxODE/issues/26

In general, I was thinking of adding:
- Resampling from a dataset (using interpolation for different observations in case it is a time-varying covariate)
- Simulation from a normal or truncated normal distribution (will assumed time invariant covariate)
- Allowing a custom function for simulating covariates.

However, I haven't yet got to this feature yet.

**Comment by KyleBarrett** [comment]
Hi Matt,
Thanks for the quick reply. I was planning on doing something like you suggested but wanted to make sure there wasn't an easier alternative.
Thanks!

Kyle
