### ISSUE TITLE
Cant run estimation routine with newest nlmixr/RxODE versions

### ISSUE THREAD

**Issue by KyleBarrett** [nlmixrdevelopment/nlmixr#75]
Hi all,

I was very excited to try out the newest version of nlmixr (Still am!), however after updating both nlmixr and RxODE I havent been able to estimate anymore.

Using the example model and dataset from nlmixr/shinyMixR:

```R
run2 <- function() {
  data = "theo_sd"
  desc = "template models"
  ref  = ""
  imp  = 1
  est  = "saem"
  control<-list()
  ini({
    tka <- .5
    tcl <- -3.2
    tv <- -1
    eta.ka ~ 1
    eta.cl ~ 2
    eta.v ~ 1
    add.err <- 0.1
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.err)
  })
}
````
fit <- nlmixr(object=run2,data = theo_sd,est="saem",control = saemControl(print=50))
![image](https://user-images.githubusercontent.com/39305051/44931352-53745080-ad2f-11e8-9f70-15209c9371b5.png)
![image](https://user-images.githubusercontent.com/39305051/44931381-69821100-ad2f-11e8-8a1d-ed8c9b89915f.png)

#SessionInfo
![image](https://user-images.githubusercontent.com/39305051/44931420-89193980-ad2f-11e8-9c74-e3800116e5f9.png)

Im wondering if snakeCharmR or another package dependency needs to be updated in addition to nlmixr and RxODE?

Thanks,
Kyle

**Comment by mattfidler** [comment]
Hi Kyle,

For the new version of nlmixr you will also have to update n1qn1:

```R
devtools::install("nlmixrdevelopment/n1qn1")
```

I'm unsure why `SnakeCharmR` is not working for you, however you could try `reticulate`.  I just started adding support for `reticulate` because `SnakeCharmR` has a orphaned maintainer (according to [CRAN](https://cran.r-project.org/web/packages/SnakeCharmR/index.html))

**Comment by mattfidler** [comment]
Also there have been some important recent updates;  If you haven't updated, pleas update nlmixr and RxODE too.

**Comment by KyleBarrett** [comment]
Hi Matt,

I haven't gotten a chance to try reticulate yet, but repeated the same procedure on my personal macbook and got similar results:

![image](https://user-images.githubusercontent.com/39305051/45108063-8b054300-b109-11e8-94b2-d618a5a05593.png)

I am up to date with n1qn1, nlmixr, RxODE, Rcpp, and RcppArmadillo in both setups. I can attach sessionInfo from my mac too if it helps.

Best,
Kyle

**Comment by KyleBarrett** [comment]
![image](https://user-images.githubusercontent.com/39305051/45116214-0671ef00-b120-11e8-9faa-8b75c252e9c3.png)

**Comment by mattfidler** [comment]
Hi @KyleBarrett,

This error is because I forgot to merge the development branch into the main branch for nlmixr.  It has been merged and should work now.  It would be a good idea to try updating everything, though, just in case something is out of sync, that is:

```R
devtools::install_github("nlmixrdevelopment/nlmixr")
devtools::install_github("nlmixrdevelopment/RxODE")
devtools::install_github("nlmixrdevelopment/nlmixr")
```

Let me know if it works on your macbook.

**Comment by KyleBarrett** [comment]
Hi Matt,

Thanks so much! Just to confirm, you mentioned nlmixr twice in your previous comment. Did you mean n1qn1 or snakeCharmR instead?

**Comment by mattfidler** [comment]
Hi @KyleBarrett,

> Did you mean n1qn1 or snakeCharmR instead?

I meant `n1qn1`, though it probably was updated.

>Why isn't the objective function being calculated?

This is a new "feature".  We are working on a generalized SAEM likelihood that would be returned here.  Right now it is experimental.  You can turn it on by adding:

```R
saem_cont <- saemControl(n.burn=50,n.em=100,print=50,logLik=TRUE)
```

One other thing you might notice is that `CWRES` are no longer present. We added `NPDE` predictions and decided to drop adding `CWRES` by default and allow you to pick.

You can request both the  `CWRES` and `NPDE` with a table option:
```R
tableC <- tableControl(cwres=TRUE,npde=TRUE)
fit.s <- nlmixr(mod,data=tmp,est="saem",control=saem_cont, table=tableC)
fit.f <- nlmixr(mod,data=tmp,est="focei",control = focei_cont, table=tableC)
```
Note that when you add the CWRES, nlmixr will also add the FOCEi objective function.  This is because nlmixr calculated everything it needs for this objective function.

If you forget the CWRES and/or NPDE you can always add them to the fit after it was completed:
```R
fit.s <- fit.s %>% addCwres() %>% addNpde()
fit.f <- fit.f %>% addNpde() # CWRES is included since it is now easy to calculate
```

> As an aside, I have gotten this error periodically in this update:
Yes.  In R you can use the command `rxClean()` to remove these files.

**Comment by KyleBarrett** [comment]
Hi Matt,

First, I got it to work on my mac. Works great!

However this was about a week ago and I didnt get a chance to play with it much since I work on a linux based server during the day. We followed the same procedure for updating packages. FOCEI worked like a charm, however I get an issue with saem at the last possible minute. I have tested this with multiple models/datasets and get the same error. I can provide more information if it'll help but just in case the error jumps out at you I only provided the error message:
![image](https://user-images.githubusercontent.com/39305051/45385565-205b7800-b5df-11e8-9117-c60ba30e399e.png)

Best,
Kyle

**Comment by mattfidler** [comment]
Are you using SnakCharmR

**Comment by KyleBarrett** [comment]
Hi Matt,
Funny that you asked that actually. We've been using snakeCharmR, but I noticed a "reticulate" line when running FOCEI. Will look into it tomorrow.
Are you suggesting that this error may arise from using or not using snakeCharmR?

Best,
Kyle

**Comment by mattfidler** [comment]
reticulate handles python quide differently than SnakeCharmR.  The support is new;  I have seen these errors with other people using reticulate, so I'm thinking of downgrating support.

**Comment by KyleBarrett** [comment]
Hi Matt,
Glad we at least narrowed down the issue. Much appreciated for your continued aid!

Kyle

**Comment by mattfidler** [comment]
Yes.  I am aware;  Hence a full version bump :)  Its not compatible with 0.9 objects.  This update has added a flexibility needed for further development.

**Comment by KyleBarrett** [comment]
Makes sense!
Im going to close the issue then. I'll post more specific issues if I come across them. Looking forward to the new shinyMixR update!
