### ISSUE TITLE
ObjFunc not calculated and covMethod("")

### ISSUE THREAD

**Issue by motyocska** [nlmixrdevelopment/nlmixr#91]
Matt,

running same model as in previous ticket (I think it was #88), nlmixr() with saem, I tried all covMethods, some fail some proceed and seems to calculate covariance but even with success (r will succeed), I am getting no Objfunc or AIC/BIC calculated. I do get a result for fit@omega...

Also, the covMethod("") (or " ") will get following error with saem for me using same model:

Error in match.arg(covMethod) : 
  'arg' should be one of “fim”, “r,s”, “r”, “s”

thanks,

Andras

**Comment by mattfidler** [comment]
Hi @motyocska,

You cannot actually skip the covariance calculation in `SAEM`.  Because of the way `SAEM` works the `fim` matrix is provided at the end of minimization.  Hence `control=saemControl(covMethod="")` is not currently a valid option.  

If you wish to have an objective function you have 2 options:
1. `control=saemControl(logLik=TRUE)` -- Gives the objective function based on gaussian quadrature. Not quite 100% stable (there is a pesky R crash that we cannot reliable reproduce yet), but we will enable this once we stablize the method
2. `table=table(cwres=TRUE)` -- In addition to calculating the conditional weighted residuals `CWRES`, weighted residuals `WRES`, and other interesting quantities (`CPRED` and `CRES`) it adds the NONMEM-compatible FOCEi objective function.

For now I suggest option 2.  

For me, the caluclation of the FOCEi piece is slightly expensive for your model, but gives these nice objective function at the end of the optimization.  It is also the first step to running the `FOCEi` fit.

**Comment by motyocska** [comment]
great thanks for the tips and teaching, working nicely... Andras

**Comment by mattfidler** [comment]
Some other items you may be interested in are NPDE/EPRED;  You can also add them by `table=tableControl(cwres=TRUE,npde=TRUE)`

If you forgot to add either of these objects you can add them aftewards

```R
fit <- fit %>% addCwres()
fit <- fit %>% addNpde()
```
